import Header from '@/components/common/header/header'
import type { Metadata } from 'next'
import './styles/index.css'

export const metadata: Metadata = {
  title: "Cal'vani",
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
      </body>
    </html>
  )
}
